version: "3.5"
services:
  db_auth:
    container_name: postgres
    image: postgres:16.0-alpine3.18
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"